language: python

sudo: required

cache:
  - pip

python:
 - "2.7"
 - "3.5"

env:
 - DJANGO_VERSION=1.10
 - DJANGO_VERSION=1.11

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - cp example/project/settings_local.py.template example/settings_local.py
  - psql -c 'create database calaccess_processed;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d calaccess_processed
  - sudo chmod -R 777 /home/travis/build/california-civic-data-coalition/django-calaccess-processed-data/example/test-data/

script:
 - flake8 calaccess_processed
 - coverage run example/manage.py test calaccess_processed

after_success:
 - coveralls

addons:
  postgresql: "9.4"