sudo: false

language: python

cache:
  - pip

python:
 - "2.7"
 - "3.5"
 - "3.6"

addons:
  postgresql: "9.6"

env:
 - DJANGO_VERSION=1.10
 - DJANGO_VERSION=1.11

install:
 - pip install -r requirements.txt
 - pip uninstall -y Django
 - pip install -q Django==$DJANGO_VERSION

before_script:
  - cp example/project/settings_local.py.template example/settings_local.py
  - psql -c 'create database calaccess_processed;' -U postgres
  - psql -c "CREATE EXTENSION postgis;" -U postgres -d calaccess_processed

script:
 - flake8 calaccess_processed
 - coverage run example/manage.py test calaccess_processed

after_success:
 - coveralls
